#!/bin/sh
set -e

[ -n "$CI" ] && exit 0

STAGED=$(git diff --cached --name-only --diff-filter=ACM || true)

[ -z "$STAGED" ] && exit 0

echo "$STAGED" | xargs oxfmt
echo "$STAGED" | xargs oxlint --fix
echo "$STAGED" | xargs git add
