name: Setup
description: Checkout, install Bun, and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: "24"
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"
    - run: bun ci
      shell: bash
