name: publish-to-vercel
on:
  workflow_call:
    inputs:
      is-preview:
        description: 'Is this a preview deployment?'
        default: true
        required: false
        type: boolean
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.2.2
      - run: pnpm install --frozen-lockfile
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.is-preview && 'preview' || 'production'}} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} ${{ !inputs.is-preview && '--prod'}}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} ${{ !inputs.is-preview && '--prod'}}
