name: issue-publish
on:
  issues:
    types:
      - labeled
jobs:
  post_created:
    if: |
      !github.event.issue.pull_request &&
      contains(github.event.issue.labels.*.name, 'status/not-published')
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/deploy-to-vercel.yml
        with:
          is-preview: true
  post_published:
    if: |
      !github.event.issue.pull_request && 
      (
        contains(github.event.issue.labels.*.name, 'status/published') ||
        contains(github.event.issue.labels.*.name, 'status/archived') ||
        contains(github.event.issue.labels.*.name, 'meta/featured')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/deploy-to-vercel.yml
        with:
          is-preview: false
